@hostname = http://localhost
@port = 8765
@host = {{hostname}}:{{port}}
@contentType = application/json
@http = HTTP/1.1

### post request
POST  {{host}}/bitmonx/register?name=shavin&list=true {{http}}
Content-Type: {{contentType}}

{
    "name" : "SERVICE-PRODUCT-CATALOG",
    "mapping": "/api/v1/customer",
    "url": "http://localhost",
    "port": 1887,
    "health_check_url": "localhost:5412/health",
    "health_check_interval": 10000,
    "timeout": 10000,
    "metadata": {
        "version": "1.0.0",
        "protocol": "http"
    }
}

### deregister service instances
DELETE {{host}}/bitmonx/deregister?serviceId=1&instanceId=1 {{http}}
Content-Type: {{contentType}}

### query service instances
GET {{host}}/bitmonx/query?mapping=/api/v1/products {{http}}
Content-Type: {{contentType}}

### query the health from the instance
GET {{host}}/bitmonx/query/health?serviceId=1&instanceId=1 {{http}}
Content-Content-Type: {{contentType}}

### login
POST {{host}}/bitmonx/login {{http}}
Content-Type: {{contentType}}

{
    "username": "admin",
    "password": "admin"
}

### get registry
GET {{host}}/bitmonx/registry {{http}}
Content-Type: {{contentType}}